import logging
import os
from typing import Protocol, TypeVar

from pydantic import BaseModel

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

# Marker the workflow places in the (trusted) instruction part of the prompt.
INSUFFICIENT_MARKER = "INSUFFICIENT_EVIDENCE: True"


class ProviderTimeoutError(Exception):
    pass


class LLMProvider(Protocol):
    def generate_structured(self, prompt: str, schema: type[T]) -> T: ...


class MockLLMProvider:
    """Deterministic provider for zero-cost local runs and tests."""

    def generate_structured(self, prompt: str, schema: type[T]) -> T:
        if INSUFFICIENT_MARKER in prompt:
            data = {
                "summary": "Insufficient information to answer.",
                "requested_action": "None",
                "missing_information": "The knowledge base has no sufficiently relevant policy.",
                "recommended_next_step": "Escalate to a human operator for manual handling.",
                "confidence_category": "insufficient_evidence",
                "citations": [],
                "limitation_disclaimer": "Mock abstention response.",
            }
        else:
            data = {
                "summary": "Mock summary based on the retrieved policy context.",
                "requested_action": "Follow the cited policy.",
                "missing_information": None,
                "recommended_next_step": "Review the cited policy and approve if appropriate.",
                "confidence_category": "high",
                "citations": [],  # the workflow fills in real, retrieved sources
                "limitation_disclaimer": "Mock response; not generated by a real model.",
            }
        return schema(**data)


def get_llm_provider() -> LLMProvider:
    if os.environ.get("MOCK_MODE", "true").lower() == "true":
        return MockLLMProvider()
    raise NotImplementedError(
        "No real LLM provider is configured. Implement LLMProvider and return it here, "
        "or set MOCK_MODE=true."
    )
